In [1]:
import pandas as pd
import requests

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

In [2]:
from selenium.webdriver.chrome.options import Options

URL = "https://jpdb.io/deck?id=global"

options = Options()
options.binary_location = r"C:\Users\firas\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe"

# Launch a Chrome-based browser window
driver = webdriver.Chrome(options=options)

# Go the URL website
driver.get(URL)

# Close the window
# driver.quit()

In [81]:

driver.current_url

'https://jpdb.io/deck?id=global&offset=100#a'

In [4]:
driver.title

'Log in or Sign up – jpdb'

In [5]:
driver.page_source

'<html class="dark-mode"><head><meta http-equiv="Content-type" content="text/html; charset=utf-8"><meta http-equiv="Content-language" content="en"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"><title>Log in or Sign up – jpdb</title><link rel="stylesheet" media="screen" href="/static/be945648d268.css"><link rel="stylesheet" media="screen" href="/static/32a5a4227a9c.css"><link rel="apple-touch-icon" sizes="180x180" href="/static/533228467534.png"><link rel="icon" type="image/png" sizes="32x32" href="/static/414de0c1e6b5.png"><link rel="icon" type="image/png" sizes="16x16" href="/static/8f8d7f6ca822.png"><link rel="manifest" href="/static/9919db124702.webmanifest"><link rel="search" type="application/opensearchdescription+xml" title="jpdb" href="/static/opensearch.xml"><script defer="" type="text/javascript" src="/static/0c282812caef.js"></script><script>function oneshot(e, n, f) { var g = function() { e.removeEventListener(n, g); f(); }; e.addEventListener(n, g); } document.addEventListener("DOMContentLoaded", function() { (document.querySelectorAll("[autofocus][type=\'text\'], .autofocus[type=\'text\'], .autofocus[type=\'search\']") || []).forEach(function(e){ e.addEventListener("focusin", function() { e.setSelectionRange(0,e.value.length); }); });if ((location.hash === "" || location.hash === "#a") && (!window.performance || window.performance.navigation.type != window.performance.navigation.TYPE_BACK_FORWARD || window.scrollY === 0)) { (document.querySelectorAll(".autofocus[type=\'text\'], .autofocus[type=\'search\']") || []).forEach(function(e){e.focus(); e.setSelectionRange(0,e.value.length);}); }(document.querySelectorAll("[autofocus][type=\'submit\']") || []).forEach(function(e){ setTimeout(function() {e.focus();}, 0); });}); window.addEventListener("load", function() { setTimeout(function() { var es = Array.prototype.slice.call(document.querySelectorAll(".bugfix")); if (es.some(function(e) { return e.scrollHeight > e.clientHeight; })) { console.log("Working around broken layout on Firefox..."); (es.forEach(function(e) { e.style.height = e.scrollHeight + "px"; setTimeout(function() { e.style.removeProperty("height"); }, 0); })); } }, 0); });if (window.matchMedia) { if (window.matchMedia(\'(prefers-color-scheme: dark)\').matches) { document.documentElement.classList.add("dark-mode"); } window.matchMedia("(prefers-color-scheme: dark)").addListener(function (e) { if (e.matches) { document.documentElement.classList.add("dark-mode"); } else { document.documentElement.classList.remove("dark-mode"); } }); }</script><style>.block { display: flex; flex-wrap: wrap; } .block > div, .block > input { max-width: 24rem; margin-right: 1rem; }</style></head><body data-instant-allow-query-string=""><div class="nav"><h1 class="nav-logo"><a href="/">jpdb</a> <span style="font-size: 50%">beta</span></h1><a class="nav-item" href="/login">Login or Sign up</a></div><div class="container bugfix"><h4>Log in</h4><form action="https://accounts.google.com/o/oauth2/v2/auth" method="get" style="margin-left: 0.4rem; margin-bottom: 1.25rem;"><input type="hidden" name="client_id" value="1069650262809-9cnkdnam4kd7gb5b7n0pdlci11ed15ps.apps.googleusercontent.com"><input type="hidden" name="response_type" value="code"><input type="hidden" name="access_type" value="offline"><input type="hidden" name="prompt" value="consent"><input type="hidden" name="redirect_uri" value="https://jpdb.io/login_with_google"><input type="hidden" name="scope" value="openid email"><button type="submit" class="sign-in-with-google"><img src="/static/ef7fed26ce1d.svg" alt="Google logo"><span>Sign in with Google</span></button></form><h5>...or log in with your jpdb.io account</h5><form action="/login" method="post" class="block" style="flex-direction: column; align-items: flex-start; margin-bottom: 0.25rem;"><div style="display: flex; flex-wrap: wrap; max-width: none;"><input required="" name="username" type="text" placeholder="Username" autocomplete="username" style="flex-grow: 1; flex-basis: 1em; margin-left: 0.5rem; margin-right: 0.5rem;" value="" autofocus=""><input required="" name="password" type="password" placeholder="Password" autocomplete="current-password" style="flex-grow: 1; flex-basis: 1em; margin-left: 0.5rem; margin-right: 0.5rem;"></div><div class="checkbox" style="margin-left: 0.5rem; margin-top: -0.5rem;"><input type="checkbox" id="remember-me" name="remember-me"><label for="remember-me">Keep me logged in even after I close the browser</label></div><input type="submit" value="Log in" style="margin-left: 0.5rem;"></form><h4>Sign up</h4><form action="/register" method="post" class="block" style="margin-left: 0.5rem; margin-right: 0.5rem;"><div><input required="" name="username" type="text" placeholder="Username" autocomplete="username" value=""><input required="" name="password" type="password" placeholder="Password" autocomplete="new-password"><input required="" name="password_repeat" type="password" placeholder="Repeat password" autocomplete="new-password"><input type="submit" value="Register"></div><div><h6>Terms of use</h6><p>Remember that by using this website you agree to our <a href="/terms-of-use">terms of use</a> and to our <a href="/privacy-policy">privacy policy</a>.</p></div></form></div><hr class="bottom"><footer class="footer"><a href="/about">About</a><a href="/faq">FAQ</a><a href="/contact-us">Contact&nbsp;us</a><a href="/privacy-policy">Privacy&nbsp;policy</a><a href="/terms-of-use">Terms&nbsp;of&nbsp;use</a><a href="/changelog">Changelog</a></footer><script src="/static/ae433897feb1.js" type="module" defer=""></script></body></html>'

In [6]:
driver.refresh()

In [78]:
master = pd.DataFrame({
    'keyword':[],
    'status':[]
})

In [94]:
cards = {'keyword':[], 'status':[]}

vocab_list = driver.find_element(By.CLASS_NAME, "vocabulary-list")

# ALL CARDS
for card in vocab_list.find_elements(By.CSS_SELECTOR, ":scope > div"):

    # GENERAL DIV
    general_div = card.find_element(By.TAG_NAME, "div")

    # VOCAB SPELLING
    vocab_spelling = general_div.find_element(By.TAG_NAME, "div")

    # A TAG for vocab
    a_tag = vocab_spelling.find_element(By.TAG_NAME, "a")

    # DIV for known status
    known_div = vocab_spelling.find_element(By.TAG_NAME, "div")

    # SPECIFIC DIV for known status
    known_status = known_div.find_element(By.TAG_NAME, "div").text


    # GET KEYWORD

    # RUBY TAGS
    rubies = a_tag.find_elements(By.TAG_NAME, "ruby")

    # Build the keyword
    characters = []
    
    # For each ruby tag
    for ruby in rubies:

        # If the character is not a kanji hence has no furigana, leave it as is and add to the list
        if len(ruby.find_elements(By.TAG_NAME, "rt")) == 0:
            characters.append(ruby.text)

        # Otherwise, if it is a kanji, remove the furigana that follows, clean the string and add it to the list
        else:
            furigana = ruby.find_element(By.TAG_NAME, "rt").text

            characters.append(ruby.text.replace(furigana,"").strip())
    
    # Build the keyword from the characters
    keyword = "".join(characters)

    # Add keyword and known status to the dictionary
    cards['keyword'].append(keyword)
    cards['status'].append(known_status)

# Convert cards dictionary to Pandas dataframe
cards = pd.DataFrame(cards)

master = pd.concat([master,cards],axis='rows')

cards

   keyword        status
0        の  Never forget
1        に  Never forget
2        よ  Never forget
3        が  Never forget
4        を  Never forget
5        も  Never forget
6       んだ  Never forget
7        は  Never forget
8        で  Never forget
9       こと  Never forget
10       夢  Never forget
11       君        Locked
12      なる  Never forget
13      ある  Never forget
14      飛ぶ        Locked
15     だって  Never forget
16      って  Never forget
17     もっと  Never forget
18     どんな  Never forget
19       だ  Never forget
20      行く        Locked
21       さ  Never forget
22     あなた  Never forget
23     きっと  Never forget
24       空        Locked
25       と  Never forget
26      から  Never forget
27      見る  Never forget
28      かな  Never forget
29     一緒に  Never forget
30     変わる        Locked
31      いつ  Never forget
32      笑う        Locked
33      さあ  Never forget
34      いる  Never forget
35      この  Never forget
36      だけ  Never forget
37      まで  Never forget
38       へ  Never forget
39     だけど  Never forget
40      いま     Redundant
41       か  Never forget
42       ね  Never forget
43      思う  Never forget
44      でも  Never forget
45      言う  Never forget
46     くれる  Never forget
47     だから  Never forget
48       ん  Never forget
49     こんな  Never forget

In [95]:
master

   keyword        status
0        時        Locked
1      信じる  Never forget
2       けど  Never forget
3      小さな  Never forget
4       泣く        Locked
..     ...           ...
45      言う  Never forget
46     くれる  Never forget
47     だから  Never forget
48       ん  Never forget
49     こんな  Never forget

[588 rows x 2 columns]

In [96]:
master.to_csv(r'JPDB_all_vocabulary_knowledge_scraped.csv',index=False)