In [1]:
import streamlit as st
import pandas as pd
import numpy as np
import requests

Sentence DB Source: https://tatoeba.org/en/downloads

In [2]:
headers = {
    "Content-Type": "application/json",
    "Accept": "application/json",
    "Authorization": f"Bearer {st.secrets['JPDB_API_KEY']}"
}

In [24]:
import requests

url = "https://jpdb.io/api/v1/list-special-decks"

payload = { "fields": ["id", "name"], }

response = requests.post(url, json=payload, headers=headers)

print(response.json()['decks'])

[[4294967295, 'All vocabulary'], [1879048194, 'Blacklisted vocabulary'], [1879048193, "Vocabulary I'll never forget"]]

In [ ]:
import requests

url = "https://jpdb.io/api/v1/deck/list-vocabDulary"

payload = {
    "id": 2,
    "fetch_occurences": False,
}

response = requests.post(url, json=payload, headers=headers)

print(response.json())

{'vocabulary': [[1516320, 3218045790], [1582410, 4022421642], [1521410, 1259679396], [1441900, 2708680832], [1223650, 740987486], [1585410, 3145960709], [1521400, 1711366820], [1467720, 2428854837], [1359040, 2711624849], [1413940, 1186277676], [1459640, 2143849405], [1979930, 1467194369], [2028920, 2204744690], [1598530, 652135941], [2029080, 2204743820], [2029120, 2204768180], [1429700, 545729736], [1217900, 4247983639], [2086960, 2379595516], [1378520, 3986518776], [1242160, 1490309084], [1408370, 2611046383], [1254180, 2319289704], [2089020, 2204745995], [1008490, 2204742515], [2829960, 162546128], [2643970, 319715906], [1313580, 1661298782], [2752700, 3940738378], [1588410, 1661815850], [1003430, 394053827], [1009470, 4283028151], [1284430, 2008539177], [2831328, 4057420157], [1237820, 2780280140], [1628530, 1661086937], [1469800, 2204745125], [1582130, 304404848], [1006970, 3897411395], [1423310, 4283588866], [1288850, 895797499], [1373860, 4237708223], [1499100, 1882804209], [1529410, 1717603850], [1007310, 2546880360], [1457210, 1017810908], [1502480, 2642863956], [1420470, 2987388496], [1217700, 2745979877], [1247030, 1481025603], [1245290, 1822613285], [1012620, 3265025033], [1375610, 4283029021], [2028980, 2204748170], [1360480, 1669089489], [1259290, 3110766742], [1351360, 4225260933], [1008550, 1623766381], [1528060, 300818984], [1251870, 1569144751], [1212260, 933168246], [1529430, 3605170360], [1208870, 2019398281], [2028990, 2204742950], [1008560, 1623765511], [2029090, 2204195720], [1247250, 1713830225], [1088990, 2946684582], [1012980, 4075472354], [1188760, 895787929], [1277450, 4030106869], [2136180, 2669995130], [1454080, 2650187300], [1219910, 2725107655], [1270960, 3780098688], [1335800, 1345634016], [1002980, 3657104650], [2028940, 2204193110], [1207240, 3618718264], [1288810, 1661287907], [1315860, 2963573620], [2029010, 2204186150], [1457730, 1198595136], [1283190, 1383277865], [1002940, 3657161200], [1583460, 1371431786], [1350040, 2289671793], [1361490, 2973219284], [1602120, 3040410833], [2028950, 3980803844], [2029000, 2204749475], [1356330, 857176103], [1307500, 1787354718], [1229840, 1833911624], [1365980, 3039701473], [1008460, 547989611], [2848742, 2758481241], [1608720, 2444508969], [1309310, 4097726523], [1591900, 1137291558], [2087820, 4070793607], [1236070, 1162053595], [1591430, 3454361280], [1529440, 611170197], [1272780, 2533120165], [2844416, 3701621793], [2028930, 2204758175], [1412890, 252422062], [1224020, 1682403321], [1414150, 1010832759], [1318720, 3226576596], [1578850, 495123619], [1590100, 1883242139], [1510790, 1860281155], [1525680, 3145970714], [1251880, 1569144316], [1163420, 3338693906], [2140410, 1375180347], [1611200, 1787355153], [2846738, 4283032501]]}

In [10]:
import requests

url = "https://jpdb.io/api/v1/lookup-vocabulary"

payload = {
    "list": [[1516320, 3218045790]],
    "fields": ["spelling", "reading", "frequency_rank", "meanings"]
}

response = requests.post(url, json=payload, headers=headers)

print(response.json())

{'vocabulary_info': [['抱きしめる', 'だきしめる', 3100, ['to hug someone close; to hold someone tight; to embrace closely']]]}

In [45]:
reviews = (
    pd.read_excel('jpdb-io-2026-05-05.xlsx')
    .drop(['web_scraper_order','web_scraper_start_url',
           'pagination','data7','data8','data9','data10','data11',
           'data12','data15','data3'],axis='columns')
    )

reviews

      data data2      data4  data5 data6  data13         data14
0        の   NaN    Top 100     57   NaN     NaN   Never forget
1        に   NaN    Top 100     43   NaN     NaN   Never forget
2        よ   NaN    Top 100     43   NaN     NaN   Never forget
3        が   NaN    Top 100     34   NaN     NaN   Never forget
4        を   NaN    Top 100     34   NaN     NaN   Never forget
..     ...   ...        ...    ...   ...     ...            ...
583  おさえつけ     る  Top 40300      1   NaN  Locked            NaN
584     結ゆ    衣い  Top 45200      1     ゆ     NaN            NaN
585    大おお   げさに        NaN      1    おお     NaN  Known (lvl 5)
586    ごらく   NaN        NaN      1   NaN     NaN            NaN
587     ちい   NaN        NaN      1   NaN     NaN            NaN

[588 rows x 7 columns]

In [46]:
reviews[reviews['data'].str.contains('夢')]

    data data2     data4  data5 data6  data13        data14
10   夢ゆめ   NaN   Top 400     16    ゆめ     NaN  Never forget
72   夢ゆめ    見み  Top 5400      5    ゆめ  Locked           NaN
513  夢ゆめ     を  Top 2700      1    ゆめ  Locked           NaN

In [47]:
x = pd.read_excel('jpdb-io-2026-05-05.xlsx')

x[x['data'].str.contains('夢')]

,web_scraper_order,web_scraper_start_url,pagination,data,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,data12,data13,data14,data15
10,1778013176-11,https://jpdb.io/deck?id=global#a,NaN,夢ゆめ,NaN,dream,Top 400,16,ゆめ,Add to a deck,Review history...,Edit meanings...,Edit readings...,Edit sentence...,Edit audio...,NaN,Never forget,⋯
72,1778013179-73,https://jpdb.io/deck?id=global#a,https://jpdb.io/deck?id=global&offset=50#a,夢ゆめ,見み,to dream (of),Top 5400,5,ゆめ,Add to a deck,Review history...,Edit meanings...,Edit readings...,Edit sentence...,Edit audio...,Locked,NaN,⋯
513,1778013222-514,https://jpdb.io/deck?id=global#a,https://jpdb.io/deck?id=global&offset=500#a,夢ゆめ,を,to dream (i.e. while asleep); to have a dream...,Top 2700,1,ゆめ,Add to a deck,Review history...,Edit meanings...,Edit readings...,Edit sentence...,Edit audio...,Locked,NaN,⋯